import {API_BASE_URL, MERCHANT_ACCOUNT_API_BASE_URL} from '@env';
export const REMEMBER_ME_KEY = 'REMEMBER_ME_KEY';
export const RESET_EMAIL = 'RESET_EMAIL';
export const FIRST_TIME_USER = 'FIRST_TIME_USER';

export const APP_BASE_URL = API_BASE_URL;
export const MERCHANT_ACCOUNT_SERVICE_BASE_URL = MERCHANT_ACCOUNT_API_BASE_URL;
